# Generated by Django 5.2.2 on 2025-06-10 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resumeconversation_userprofile_savedarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeconversation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='savedarticle',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='savedarticle',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='resumeconversation',
            name='question',
        ),
        migrations.RemoveField(
            model_name='resumeconversation',
            name='response',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='career_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_uploaded',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='resumeconversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeconversation',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AddField(
            model_name='resumeconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='summary',
            field=models.TextField(default='No summary available'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('recruiter', 'Recruiter')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeconversation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='saved_at',
        ),
        migrations.RemoveField(
            model_name='savedarticle',
            name='source',
        ),
    ]
